// Package web embeds the built Temis modeler frontend (ADR-0016, WP-60) so
// temisd serves it as part of a single binary — no CDN, works offline.
//
// The dist/ tree is generated by `make web` (a Vite build of the TypeScript
// sources under web/) and committed to the repository, so a plain `go build`
// needs no Node toolchain. Regenerate it whenever the frontend sources change.
package web

import (
	"embed"
	"io/fs"
)

//go:embed dist
var dist embed.FS

// Assets returns the built frontend as a filesystem rooted at the web root, so
// "index.html" and "assets/…" resolve directly. It is suitable for
// http.FileServerFS.
func Assets() fs.FS {
	sub, err := fs.Sub(dist, "dist")
	if err != nil {
		// dist is embedded at compile time; a failure here is a build-time bug.
		panic("web: embedded dist missing: " + err.Error())
	}
	return sub
}
